In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
doc=[]
path=r"C:\Users\ASUS\Downloads\dates.txt"
with open(path,'r') as file:
    for line in file:
        doc.append(line)
    
df=pd.Series(doc)

In [3]:
df

0           03/25/93 Total time of visit (in minutes):\n
1                         6/18/85 Primary Care Doctor:\n
2      sshe plans to move as of 7/8/71 In-Home Servic...
3                  7 on 9/27/75 Audit C Score Current:\n
4      2/6/96 sleep studyPain Treatment Pain Level (N...
                             ...
495    1979 Family Psych History: Family History of S...
496    therapist and friend died in ~2006 Parental/Ca...
497                         2008 partial thyroidectomy\n
498    sPt describes a history of sexual abuse as a c...
499    . In 1980, patient was living in Naples and de...
Length: 500, dtype: object

In [4]:
month_map = {
    'January': '01', 'Jan': '01',
    'February': '02', 'Feb': '02',
    'March': '03', 'Mar': '03',
    'April': '04', 'Apr': '04',
    'May': '05',
    'June': '06', 'Jun': '06',
    'July': '07', 'Jul': '07',
    'August': '08', 'Aug': '08',
    'September': '09', 'Sep': '09',
    'October': '10', 'Oct': '10',
    'November': '11', 'Nov': '11',
    'December': '12', 'Dec': '12'
}

In [5]:
import re
dates=[]
pattern=re.compile('\d{1,2}[/-]\d{1,2}[/-]\d{2,4}')
pattern3=re.compile(r'(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\.?\-?\s?\d{1,2}(?:st|nd|rd|th)?[,-]?\s?\d{4}')
pattern5=re.compile(r'\d{1,2}(?:th|st|nd|rd)?\s?(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s?,?.?\s?\d{2,4}')
pattern6=re.compile(r'\d{1,2}[/]\d{2,4}')
pattern7=re.compile(r'\d{4}')
for text in df:
    if pattern.search(text):
        dates.append(re.findall(pattern,text)[0])
    elif pattern3.search(text):
        dates.append(re.findall(pattern3,text)[0])
    elif pattern5.search(text):
        dates.append(re.findall(pattern5,text)[0])
    elif pattern6.search(text):
        x=re.findall(pattern6,text)[0]
        y=x.split('/')
        dates.append(y[0]+'/1/'+y[1])
    elif pattern7.search(text):
        x=re.findall(pattern7,text)[0]
        dates.append('1/1/'+x)

In [6]:
dates

['03/25/93',
 '6/18/85',
 '7/8/71',
 '9/27/75',
 '2/6/96',
 '7/06/79',
 '5/18/78',
 '10/24/89',
 '3/7/86',
 '4/10/71',
 '5/11/85',
 '4/09/75',
 '8/01/98',
 '1/26/72',
 '5/24/1990',
 '1/25/2011',
 '4/12/82',
 '10/13/1976',
 '4/24/98',
 '5/21/77',
 '7/21/98',
 '10/21/79',
 '3/03/90',
 '2/11/76',
 '07/25/1984',
 '4-13-82',
 '9/22/89',
 '9/02/76',
 '9/12/71',
 '10/24/86',
 '03/31/1985',
 '7/20/72',
 '4/12/87',
 '06/20/91',
 '5/12/2012',
 '3/15/83',
 '2/14/73',
 '5/24/88',
 '7/27/1986',
 '1-14-81',
 '7-29-75',
 '6/24/87',
 '8/14/94',
 '4/13/2002',
 '8/16/82',
 '2/15/1998',
 '7/15/91',
 '06/12/94',
 '9/17/84',
 '2/28/75',
 '11/22/75',
 '5/24/91',
 '6/13/92',
 '7/11/71',
 '12/26/86',
 '10/11/1987',
 '3/14/95',
 '12/01/73',
 '12/5/2010',
 '08/20/1982',
 '7/24/95',
 '8/06/83',
 '02/22/92',
 '6/28/87',
 '07/29/1994',
 '08/11/78',
 '10/29/91',
 '7/6/91',
 '1/21/87',
 '11/3/1985',
 '7/04/82',
 '4-13-89',
 '7/11/77',
 '4/12/74',
 '09/19/81',
 '9/6/79',
 '12/5/87',
 '01/05/1999',
 '4/22/80',
 '10/04/98',
 '6/29/81',
 '8/04/78',
 '7/07/1974',
 '09/14/2000',
 '5/18/71',
 '8/09/1981',
 '6/05/93',
 '8/9/97',
 '12/8/82',
 '8/26/89',
 '10/13/95',
 '4/19/91',
 '04/08/2004',
 '9/20/76',
 '12/08/1990',
 '4/11/1974',
 '7/18/86',
 '3/31/91',
 '5/13/72',
 '11/14/83',
 '8/16/92',
 '10/05/97',
 '07/18/2002',
 '9/22/82',
 '2/24/74',
 '2/03/78',
 '2/11/2006',
 '8/22/83',
 '5/04/74',
 '7/20/2011',
 '6/17/95',
 '6/10/72',
 '10/16/82',
 '12/15/92',
 '12/8/97',
 '4/05/89',
 '12/04/87',
 '6/20/77',
 '4/27/2006',
 '07/17/92',
 '12/22/98',
 '10/02/96',
 '11/05/90',
 '5/04/77',
 '2/27/96',
 '24 Jan 2001',
 '10 Sep 2004',
 '26 May 1982',
 '28 June 2002',
 '06 May 1972',
 '25 Oct 1987',
 '14 Oct 1996',
 '30 Nov 2007',
 '28 June 1994',
 '14 Jan 1981',
 '10 Oct 1985',
 '11 February 1985',
 '10 Feb 1983',
 '05 Feb 1992',
 '21 Oct 2012',
 '14 Feb 1995',
 '30 May 2016',
 '22 Jan 1996',
 '14 Oct 1992',
 '06 Oct 2003',
 '18 Oct 1999',
 '11 Nov 2004',
 '30 May 2001',
 '02 Feb 1978',
 '09 Sep 1989',
 '12 March 1980',
 '22 June 1990',
 '28 Sep 2015',
 '13 Jan 1972',
 '06 Mar 1974',
 '10 Oct 1974',
 '26 May 1974',
 '10 Feb 1990',
 '23 Aug 2000',
 '26 May 2001',
 '21 Oct 2007',
 '19 Oct 2016',
 '05 Mar 1974',
 '29 Jan 1994',
 '21 Oct 1978',
 '18 August 1975',
 '11 Nov 1996',
 '01 Oct 1979',
 '13 Oct 1986',
 '21 Oct 1995',
 '24 Jan 2011',
 '04 Oct 1972',
 '23 Aug 1993',
 '18 Oct 2006',
 '04 Dec 1988',
 '21 Oct 1983',
 '26 May 2010',
 '18 Jan 1990',
 '15 Jun 1985',
 '10 Dec 1982',
 '09 Dec 1988',
 '18 August 1995',
 '13 June 1974',
 '26 May 2008',
 '11 Nov 2002',
 '17 Aug 1985',
 '13 Oct 2016',
 '14 Jan 2008',
 '12 March 2004',
 '21 Oct 1977',
 '10 Aug 2000',
 '30 Nov 1972',
 '06 May 1993',
 '18 Jan 1995',
 'April 11, 1990',
 'May 30, 2001',
 'Feb 18, 1994',
 'February 18, 1981',
 'October. 11, 2013',
 'Jan 24 1986',
 'July 26, 1978',
 'December 23, 1999',
 'May 15, 1989',
 'September 06, 1995',
 'Mar. 10, 1976',
 'Jan 27, 1983',
 'October 23 1990',
 'August 12 2004',
 'September 01, 2012',
 'July 25, 1983',
 'August 11, 1989',
 'April 17, 1992',
 'July 24, 1999',
 'July 11, 1997',
 'Sep. 10, 1974',
 'August 14, 1981',
 'Nov 11, 1988',
 'June 13, 2011',
 'May 14, 1989',
 'Dec 14 1975',
 'June 25, 2012',
 'Oct 18, 1980',
 'May 15, 1998',
 'October 14 1974',
 'July 25, 1998',
 'June 15, 1972',
 'January 07, 1991',
 'September. 15, 2011',
 '1/1/1985',
 '1/1/2011',
 '1/1/1986',
 '1/1/2016',
 '1/1/1977',
 '1/1/1990',
 '1/1/2003',
 '1/1/2015',
 '1/1/1995',
 '1/1/1976',
 '1/1/1995',
 '1/1/1978',
 '1/1/2011',
 '1/1/2004',
 '1/1/2010',
 '1/1/2012',
 '1/1/2013',
 '1/1/1990',
 '1/1/1981',
 '1/1/1983',
 '1/1/1995',
 '1/1/1993',
 '1/1/2005',
 '1/1/1998',
 '1/1/2007',
 '1/1/2016',
 '1/1/1979',
 '1/1/2014',
 '1/1/1988',
 '1/1/2015',
 '1/1/1976',
 '1/1/1979',
 '1/1/2000',
 '1/1/1986',
 '1/1/2002',
 '1/1/1981',
 '1/1/2007',
 '1/1/1989',
 '1/1/1999',
 '1/1/1980',
 '1/1/2009',
 '1/1/1992',
 '1/1/2006',
 '1/1/7787',
 '1/1/1993',
 '1/1/2010',
 '1/1/1985',
 '1/1/1984',
 '1/1/1986',
 '1/1/2007',
 '1/1/1974',
 '1/1/2013',
 '1/1/1985',
 '1/1/2004',
 '1/1/2012',
 '1/1/1977',
 '1/1/1987',
 '1/1/1983',
 '1/1/2013',
 '1/1/2010',
 '1/1/2009',
 '1/1/2007',
 '1/1/2011',
 '1/1/2004',
 '1/1/1995',
 '1/1/2008',
 '1/1/1983',
 '1/1/1983',
 '1/1/1979',
 '1/1/2009',
 '1/1/1993',
 '1/1/1974',
 '1/1/1994',
 '1/1/1992',
 '1/1/2004',
 '1/1/1977',
 '1/1/2002',
 '1/1/2000',
 '1/1/2004',
 '1/1/2006',
 '1/1/1994',
 '1/1/1977',
 '1/1/1992',
 '1/1/1995',
 '1/1/1989',
 '1/1/1978',
 '1/1/2007',
 '1/1/1976',
 '1/1/2011',
 '1/1/1975',
 '1/1/1978',
 '1/1/1975',
 '1/1/2012',
 '2June, 1999',
 '1/1/1991',
 '1/1/1973',
 '1/1/1996',
 '1/1/2007',
 '1/1/1995',
 '1/1/1999',
 '1/1/2001',
 '1/1/2000',
 '1/1/1988',
 '1/1/1993',
 '1/1/1974',
 '1/1/1997',
 '1/1/1986',
 '1/1/1973',
 '1/1/1978',
 '1/1/2007',
 '1/1/1998',
 '1/1/2005',
 '1/1/1980',
 '1/1/2007',
 '1/1/1976',
 '6/1/1998',
 '6/1/2005',
 '10/1/1973',
 '9/1/2005',
 '03/1/1980',
 '12/1/2005',
 '5/1/1987',
 '5/1/2004',
 '8/1/1974',
 '3/1/1986',
 '10/1/1997',
 '3/1/1993',
 '3/1/1981',
 '9/1/2003',
 '10/1/1993',
 '1/1/1983',
 '7/1/1994',
 '12/1/2008',
 '10/1/1980',
 '8/1/2003',
 '12/1/1975',
 '11/1/2010',
 '7/1/1997',
 '7/1/2014',
 '9/1/2001',
 '8/1/1986',
 '1/1/1978',
 '9/1/1975',
 '1/1/2009',
 '5/1/1995',
 '8/1/1989',
 '11/1/2000',
 '06/1/1973',
 '2/1/1999',
 '6/1/2001',
 '12/1/1978',
 '8/1/2009',
 '7/1/1973',
 '1/1/2014',
 '09/1/1975',
 '12/1/2012',
 '5/1/1999',
 '7/1/1989',
 '7/1/2009',
 '11/1/1998',
 '3/1/1995',
 '2/1/2009',
 '08/1/1988',
 '4/1/2007',
 '5/1/2000',
 '4/1/2012',
 '10/1/2001',
 '2/1/1977',
 '8/1/2008',
 '2/1/1983',
 '5/1/1979',
 '1/1/1992',
 '11/1/2008',
 '12/1/2014',
 '4/1/1974',
 '10/1/1981',
 '10/1/1986',
 '03/1/1973',
 '12/1/1994',
 '8/1/1999',
 '10/1/2010',
 '10/1/1994',
 '01/1/2007',
 '8/1/2010',
 '03/1/1990',
 '11/1/2016',
 '4/1/2004',
 '2/1/1973',
 '7/1/1987',
 '8/1/2000',
 '8/1/1975',
 '5/1/1977',
 '3/1/2000',
 '9/1/1984',
 '4/1/1973',
 '12/1/1986',
 '4/1/1979',
 '7/1/2004',
 '11/1/1984',
 '5/1/2016',
 '12/1/2007',
 '11/1/1982',
 '06/1/1981',
 '4/1/2013',
 '4/1/1999',
 '5/1/2006',
 '10/1/1978',
 '12/1/1989',
 '2/1/1974',
 '11/1/1986',
 '4/1/1983',
 '10/1/2014',
 '6/1/1989',
 '9/1/1980',
 '9/1/1992',
 '9/1/2000',
 '7/1/1981',
 '1/1/2008',
 '4/1/2002',
 '7/1/1985',
 '5/1/2010',
 '8/1/2002',
 '1/1/1994',
 '12/1/2004',
 '3/1/2003',
 '7/1/1991',
 '7/1/1982',
 '1/1/1984',
 '1/1/2000',
 '1/1/2001',
 '1/1/1982',
 '1/1/1998',
 '1/1/2012',
 '1/1/1991',
 '1/1/1988',
 '1/1/2014',
 '1/1/2016',
 '1/1/1976',
 '1/1/1981',
 '1/1/2011',
 '1/1/1997',
 '1/1/2003',
 '1/1/1983',
 '1/1/1999',
 '1/1/2010',
 '1/1/1975',
 '1/1/1972',
 '1/1/2015',
 '1/1/1989',
 '1/1/1994',
 '1/1/1993',
 '1/1/1996',
 '1/1/2013',
 '1/1/1974',
 '1/1/1990',
 '1/1/1995',
 '1/1/2004',
 '1/1/1987',
 '1/1/1973',
 '1/1/1992',
 '1/1/1977',
 '1/1/1985',
 '1/1/2007',
 '1/1/2009',
 '1/1/1986',
 '1/1/1978',
 '1/1/2002',
 '1/1/1979',
 '1/1/2006',
 '1/1/2008',
 '1/1/2005',
 '1/1/1980']

In [7]:
s=pd.Series(dates)

In [8]:
s.values

array(['03/25/93', '6/18/85', '7/8/71', '9/27/75', '2/6/96', '7/06/79',
       '5/18/78', '10/24/89', '3/7/86', '4/10/71', '5/11/85', '4/09/75',
       '8/01/98', '1/26/72', '5/24/1990', '1/25/2011', '4/12/82',
       '10/13/1976', '4/24/98', '5/21/77', '7/21/98', '10/21/79',
       '3/03/90', '2/11/76', '07/25/1984', '4-13-82', '9/22/89',
       '9/02/76', '9/12/71', '10/24/86', '03/31/1985', '7/20/72',
       '4/12/87', '06/20/91', '5/12/2012', '3/15/83', '2/14/73',
       '5/24/88', '7/27/1986', '1-14-81', '7-29-75', '6/24/87', '8/14/94',
       '4/13/2002', '8/16/82', '2/15/1998', '7/15/91', '06/12/94',
       '9/17/84', '2/28/75', '11/22/75', '5/24/91', '6/13/92', '7/11/71',
       '12/26/86', '10/11/1987', '3/14/95', '12/01/73', '12/5/2010',
       '08/20/1982', '7/24/95', '8/06/83', '02/22/92', '6/28/87',
       '07/29/1994', '08/11/78', '10/29/91', '7/6/91', '1/21/87',
       '11/3/1985', '7/04/82', '4-13-89', '7/11/77', '4/12/74',
       '09/19/81', '9/6/79', '12/5/87', '01/05/1999', '4/22/80',
       '10/04/98', '6/29/81', '8/04/78', '7/07/1974', '09/14/2000',
       '5/18/71', '8/09/1981', '6/05/93', '8/9/97', '12/8/82', '8/26/89',
       '10/13/95', '4/19/91', '04/08/2004', '9/20/76', '12/08/1990',
       '4/11/1974', '7/18/86', '3/31/91', '5/13/72', '11/14/83',
       '8/16/92', '10/05/97', '07/18/2002', '9/22/82', '2/24/74',
       '2/03/78', '2/11/2006', '8/22/83', '5/04/74', '7/20/2011',
       '6/17/95', '6/10/72', '10/16/82', '12/15/92', '12/8/97', '4/05/89',
       '12/04/87', '6/20/77', '4/27/2006', '07/17/92', '12/22/98',
       '10/02/96', '11/05/90', '5/04/77', '2/27/96', '24 Jan 2001',
       '10 Sep 2004', '26 May 1982', '28 June 2002', '06 May 1972',
       '25 Oct 1987', '14 Oct 1996', '30 Nov 2007', '28 June 1994',
       '14 Jan 1981', '10 Oct 1985', '11 February 1985', '10 Feb 1983',
       '05 Feb 1992', '21 Oct 2012', '14 Feb 1995', '30 May 2016',
       '22 Jan 1996', '14 Oct 1992', '06 Oct 2003', '18 Oct 1999',
       '11 Nov 2004', '30 May 2001', '02 Feb 1978', '09 Sep 1989',
       '12 March 1980', '22 June 1990', '28 Sep 2015', '13 Jan 1972',
       '06 Mar 1974', '10 Oct 1974', '26 May 1974', '10 Feb 1990',
       '23 Aug 2000', '26 May 2001', '21 Oct 2007', '19 Oct 2016',
       '05 Mar 1974', '29 Jan 1994', '21 Oct 1978', '18 August 1975',
       '11 Nov 1996', '01 Oct 1979', '13 Oct 1986', '21 Oct 1995',
       '24 Jan 2011', '04 Oct 1972', '23 Aug 1993', '18 Oct 2006',
       '04 Dec 1988', '21 Oct 1983', '26 May 2010', '18 Jan 1990',
       '15 Jun 1985', '10 Dec 1982', '09 Dec 1988', '18 August 1995',
       '13 June 1974', '26 May 2008', '11 Nov 2002', '17 Aug 1985',
       '13 Oct 2016', '14 Jan 2008', '12 March 2004', '21 Oct 1977',
       '10 Aug 2000', '30 Nov 1972', '06 May 1993', '18 Jan 1995',
       'April 11, 1990', 'May 30, 2001', 'Feb 18, 1994',
       'February 18, 1981', 'October. 11, 2013', 'Jan 24 1986',
       'July 26, 1978', 'December 23, 1999', 'May 15, 1989',
       'September 06, 1995', 'Mar. 10, 1976', 'Jan 27, 1983',
       'October 23 1990', 'August 12 2004', 'September 01, 2012',
       'July 25, 1983', 'August 11, 1989', 'April 17, 1992',
       'July 24, 1999', 'July 11, 1997', 'Sep. 10, 1974',
       'August 14, 1981', 'Nov 11, 1988', 'June 13, 2011', 'May 14, 1989',
       'Dec 14 1975', 'June 25, 2012', 'Oct 18, 1980', 'May 15, 1998',
       'October 14 1974', 'July 25, 1998', 'June 15, 1972',
       'January 07, 1991', 'September. 15, 2011', '1/1/1985', '1/1/2011',
       '1/1/1986', '1/1/2016', '1/1/1977', '1/1/1990', '1/1/2003',
       '1/1/2015', '1/1/1995', '1/1/1976', '1/1/1995', '1/1/1978',
       '1/1/2011', '1/1/2004', '1/1/2010', '1/1/2012', '1/1/2013',
       '1/1/1990', '1/1/1981', '1/1/1983', '1/1/1995', '1/1/1993',
       '1/1/2005', '1/1/1998', '1/1/2007', '1/1/2016', '1/1/1979',
       '1/1/2014', '1/1/1988', '1/1/2015', '1/1/1976', '1/1/1979',
       '1/1/2000', '1/1/1986', '1/1/2002', '1/1/1981', '1/1/2007',
       '1/1/1989', '1/1/1999', '1/1/1980', '1/1/2009', '1/1/1992',
       '1/1/2006', '1/1/7787', '1/1/1993', '1/1/2010', '1/1/1985',
       '1/1/1984', '1/1/1986', '1/1/2007', '1/1/1974', '1/1/2013',
       '1/1/1985', '1/1/2004', '1/1/2012', '1/1/1977', '1/1/1987',
       '1/1/1983', '1/1/2013', '1/1/2010', '1/1/2009', '1/1/2007',
       '1/1/2011', '1/1/2004', '1/1/1995', '1/1/2008', '1/1/1983',
       '1/1/1983', '1/1/1979', '1/1/2009', '1/1/1993', '1/1/1974',
       '1/1/1994', '1/1/1992', '1/1/2004', '1/1/1977', '1/1/2002',
       '1/1/2000', '1/1/2004', '1/1/2006', '1/1/1994', '1/1/1977',
       '1/1/1992', '1/1/1995', '1/1/1989', '1/1/1978', '1/1/2007',
       '1/1/1976', '1/1/2011', '1/1/1975', '1/1/1978', '1/1/1975',
       '1/1/2012', '2June, 1999', '1/1/1991', '1/1/1973', '1/1/1996',
       '1/1/2007', '1/1/1995', '1/1/1999', '1/1/2001', '1/1/2000',
       '1/1/1988', '1/1/1993', '1/1/1974', '1/1/1997', '1/1/1986',
       '1/1/1973', '1/1/1978', '1/1/2007', '1/1/1998', '1/1/2005',
       '1/1/1980', '1/1/2007', '1/1/1976', '6/1/1998', '6/1/2005',
       '10/1/1973', '9/1/2005', '03/1/1980', '12/1/2005', '5/1/1987',
       '5/1/2004', '8/1/1974', '3/1/1986', '10/1/1997', '3/1/1993',
       '3/1/1981', '9/1/2003', '10/1/1993', '1/1/1983', '7/1/1994',
       '12/1/2008', '10/1/1980', '8/1/2003', '12/1/1975', '11/1/2010',
       '7/1/1997', '7/1/2014', '9/1/2001', '8/1/1986', '1/1/1978',
       '9/1/1975', '1/1/2009', '5/1/1995', '8/1/1989', '11/1/2000',
       '06/1/1973', '2/1/1999', '6/1/2001', '12/1/1978', '8/1/2009',
       '7/1/1973', '1/1/2014', '09/1/1975', '12/1/2012', '5/1/1999',
       '7/1/1989', '7/1/2009', '11/1/1998', '3/1/1995', '2/1/2009',
       '08/1/1988', '4/1/2007', '5/1/2000', '4/1/2012', '10/1/2001',
       '2/1/1977', '8/1/2008', '2/1/1983', '5/1/1979', '1/1/1992',
       '11/1/2008', '12/1/2014', '4/1/1974', '10/1/1981', '10/1/1986',
       '03/1/1973', '12/1/1994', '8/1/1999', '10/1/2010', '10/1/1994',
       '01/1/2007', '8/1/2010', '03/1/1990', '11/1/2016', '4/1/2004',
       '2/1/1973', '7/1/1987', '8/1/2000', '8/1/1975', '5/1/1977',
       '3/1/2000', '9/1/1984', '4/1/1973', '12/1/1986', '4/1/1979',
       '7/1/2004', '11/1/1984', '5/1/2016', '12/1/2007', '11/1/1982',
       '06/1/1981', '4/1/2013', '4/1/1999', '5/1/2006', '10/1/1978',
       '12/1/1989', '2/1/1974', '11/1/1986', '4/1/1983', '10/1/2014',
       '6/1/1989', '9/1/1980', '9/1/1992', '9/1/2000', '7/1/1981',
       '1/1/2008', '4/1/2002', '7/1/1985', '5/1/2010', '8/1/2002',
       '1/1/1994', '12/1/2004', '3/1/2003', '7/1/1991', '7/1/1982',
       '1/1/1984', '1/1/2000', '1/1/2001', '1/1/1982', '1/1/1998',
       '1/1/2012', '1/1/1991', '1/1/1988', '1/1/2014', '1/1/2016',
       '1/1/1976', '1/1/1981', '1/1/2011', '1/1/1997', '1/1/2003',
       '1/1/1983', '1/1/1999', '1/1/2010', '1/1/1975', '1/1/1972',
       '1/1/2015', '1/1/1989', '1/1/1994', '1/1/1993', '1/1/1996',
       '1/1/2013', '1/1/1974', '1/1/1990', '1/1/1995', '1/1/2004',
       '1/1/1987', '1/1/1973', '1/1/1992', '1/1/1977', '1/1/1985',
       '1/1/2007', '1/1/2009', '1/1/1986', '1/1/1978', '1/1/2002',
       '1/1/1979', '1/1/2006', '1/1/2008', '1/1/2005', '1/1/1980'],
      dtype=object)

In [9]:
import string
p=string.punctuation
p

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [10]:
d2=[]
for date in s:
    if len(date.split(' '))>1:
        if date[0].isalpha():
            str=''
            for char in date:
                if char not in p:
                    str+=char
            x=str.split(' ')
            x[0]=month_map.get(x[0],x[0])
            new_str=x[0]+'/'+'/'.join(x[1:])
            d2.append(new_str)          
        else:
            str=''
            for char in date:
                if char not in p:
                    str+=char
                    
            x=str.split(' ')
            
            if len(x)==2:
                d2.append('6/2/1999')
            else:
                x[1]=month_map.get(x[1],x[1])
                new_str=x[1]+'/'+x[0]+'/'+x[2]
                d2.append(new_str)
            
    else:
        d2.append(date)

In [11]:
d2

['03/25/93',
 '6/18/85',
 '7/8/71',
 '9/27/75',
 '2/6/96',
 '7/06/79',
 '5/18/78',
 '10/24/89',
 '3/7/86',
 '4/10/71',
 '5/11/85',
 '4/09/75',
 '8/01/98',
 '1/26/72',
 '5/24/1990',
 '1/25/2011',
 '4/12/82',
 '10/13/1976',
 '4/24/98',
 '5/21/77',
 '7/21/98',
 '10/21/79',
 '3/03/90',
 '2/11/76',
 '07/25/1984',
 '4-13-82',
 '9/22/89',
 '9/02/76',
 '9/12/71',
 '10/24/86',
 '03/31/1985',
 '7/20/72',
 '4/12/87',
 '06/20/91',
 '5/12/2012',
 '3/15/83',
 '2/14/73',
 '5/24/88',
 '7/27/1986',
 '1-14-81',
 '7-29-75',
 '6/24/87',
 '8/14/94',
 '4/13/2002',
 '8/16/82',
 '2/15/1998',
 '7/15/91',
 '06/12/94',
 '9/17/84',
 '2/28/75',
 '11/22/75',
 '5/24/91',
 '6/13/92',
 '7/11/71',
 '12/26/86',
 '10/11/1987',
 '3/14/95',
 '12/01/73',
 '12/5/2010',
 '08/20/1982',
 '7/24/95',
 '8/06/83',
 '02/22/92',
 '6/28/87',
 '07/29/1994',
 '08/11/78',
 '10/29/91',
 '7/6/91',
 '1/21/87',
 '11/3/1985',
 '7/04/82',
 '4-13-89',
 '7/11/77',
 '4/12/74',
 '09/19/81',
 '9/6/79',
 '12/5/87',
 '01/05/1999',
 '4/22/80',
 '10/04/98',
 '6/29/81',
 '8/04/78',
 '7/07/1974',
 '09/14/2000',
 '5/18/71',
 '8/09/1981',
 '6/05/93',
 '8/9/97',
 '12/8/82',
 '8/26/89',
 '10/13/95',
 '4/19/91',
 '04/08/2004',
 '9/20/76',
 '12/08/1990',
 '4/11/1974',
 '7/18/86',
 '3/31/91',
 '5/13/72',
 '11/14/83',
 '8/16/92',
 '10/05/97',
 '07/18/2002',
 '9/22/82',
 '2/24/74',
 '2/03/78',
 '2/11/2006',
 '8/22/83',
 '5/04/74',
 '7/20/2011',
 '6/17/95',
 '6/10/72',
 '10/16/82',
 '12/15/92',
 '12/8/97',
 '4/05/89',
 '12/04/87',
 '6/20/77',
 '4/27/2006',
 '07/17/92',
 '12/22/98',
 '10/02/96',
 '11/05/90',
 '5/04/77',
 '2/27/96',
 '01/24/2001',
 '09/10/2004',
 '05/26/1982',
 '06/28/2002',
 '05/06/1972',
 '10/25/1987',
 '10/14/1996',
 '11/30/2007',
 '06/28/1994',
 '01/14/1981',
 '10/10/1985',
 '02/11/1985',
 '02/10/1983',
 '02/05/1992',
 '10/21/2012',
 '02/14/1995',
 '05/30/2016',
 '01/22/1996',
 '10/14/1992',
 '10/06/2003',
 '10/18/1999',
 '11/11/2004',
 '05/30/2001',
 '02/02/1978',
 '09/09/1989',
 '03/12/1980',
 '06/22/1990',
 '09/28/2015',
 '01/13/1972',
 '03/06/1974',
 '10/10/1974',
 '05/26/1974',
 '02/10/1990',
 '08/23/2000',
 '05/26/2001',
 '10/21/2007',
 '10/19/2016',
 '03/05/1974',
 '01/29/1994',
 '10/21/1978',
 '08/18/1975',
 '11/11/1996',
 '10/01/1979',
 '10/13/1986',
 '10/21/1995',
 '01/24/2011',
 '10/04/1972',
 '08/23/1993',
 '10/18/2006',
 '12/04/1988',
 '10/21/1983',
 '05/26/2010',
 '01/18/1990',
 '06/15/1985',
 '12/10/1982',
 '12/09/1988',
 '08/18/1995',
 '06/13/1974',
 '05/26/2008',
 '11/11/2002',
 '08/17/1985',
 '10/13/2016',
 '01/14/2008',
 '03/12/2004',
 '10/21/1977',
 '08/10/2000',
 '11/30/1972',
 '05/06/1993',
 '01/18/1995',
 '04/11/1990',
 '05/30/2001',
 '02/18/1994',
 '02/18/1981',
 '10/11/2013',
 '01/24/1986',
 '07/26/1978',
 '12/23/1999',
 '05/15/1989',
 '09/06/1995',
 '03/10/1976',
 '01/27/1983',
 '10/23/1990',
 '08/12/2004',
 '09/01/2012',
 '07/25/1983',
 '08/11/1989',
 '04/17/1992',
 '07/24/1999',
 '07/11/1997',
 '09/10/1974',
 '08/14/1981',
 '11/11/1988',
 '06/13/2011',
 '05/14/1989',
 '12/14/1975',
 '06/25/2012',
 '10/18/1980',
 '05/15/1998',
 '10/14/1974',
 '07/25/1998',
 '06/15/1972',
 '01/07/1991',
 '09/15/2011',
 '1/1/1985',
 '1/1/2011',
 '1/1/1986',
 '1/1/2016',
 '1/1/1977',
 '1/1/1990',
 '1/1/2003',
 '1/1/2015',
 '1/1/1995',
 '1/1/1976',
 '1/1/1995',
 '1/1/1978',
 '1/1/2011',
 '1/1/2004',
 '1/1/2010',
 '1/1/2012',
 '1/1/2013',
 '1/1/1990',
 '1/1/1981',
 '1/1/1983',
 '1/1/1995',
 '1/1/1993',
 '1/1/2005',
 '1/1/1998',
 '1/1/2007',
 '1/1/2016',
 '1/1/1979',
 '1/1/2014',
 '1/1/1988',
 '1/1/2015',
 '1/1/1976',
 '1/1/1979',
 '1/1/2000',
 '1/1/1986',
 '1/1/2002',
 '1/1/1981',
 '1/1/2007',
 '1/1/1989',
 '1/1/1999',
 '1/1/1980',
 '1/1/2009',
 '1/1/1992',
 '1/1/2006',
 '1/1/7787',
 '1/1/1993',
 '1/1/2010',
 '1/1/1985',
 '1/1/1984',
 '1/1/1986',
 '1/1/2007',
 '1/1/1974',
 '1/1/2013',
 '1/1/1985',
 '1/1/2004',
 '1/1/2012',
 '1/1/1977',
 '1/1/1987',
 '1/1/1983',
 '1/1/2013',
 '1/1/2010',
 '1/1/2009',
 '1/1/2007',
 '1/1/2011',
 '1/1/2004',
 '1/1/1995',
 '1/1/2008',
 '1/1/1983',
 '1/1/1983',
 '1/1/1979',
 '1/1/2009',
 '1/1/1993',
 '1/1/1974',
 '1/1/1994',
 '1/1/1992',
 '1/1/2004',
 '1/1/1977',
 '1/1/2002',
 '1/1/2000',
 '1/1/2004',
 '1/1/2006',
 '1/1/1994',
 '1/1/1977',
 '1/1/1992',
 '1/1/1995',
 '1/1/1989',
 '1/1/1978',
 '1/1/2007',
 '1/1/1976',
 '1/1/2011',
 '1/1/1975',
 '1/1/1978',
 '1/1/1975',
 '1/1/2012',
 '6/2/1999',
 '1/1/1991',
 '1/1/1973',
 '1/1/1996',
 '1/1/2007',
 '1/1/1995',
 '1/1/1999',
 '1/1/2001',
 '1/1/2000',
 '1/1/1988',
 '1/1/1993',
 '1/1/1974',
 '1/1/1997',
 '1/1/1986',
 '1/1/1973',
 '1/1/1978',
 '1/1/2007',
 '1/1/1998',
 '1/1/2005',
 '1/1/1980',
 '1/1/2007',
 '1/1/1976',
 '6/1/1998',
 '6/1/2005',
 '10/1/1973',
 '9/1/2005',
 '03/1/1980',
 '12/1/2005',
 '5/1/1987',
 '5/1/2004',
 '8/1/1974',
 '3/1/1986',
 '10/1/1997',
 '3/1/1993',
 '3/1/1981',
 '9/1/2003',
 '10/1/1993',
 '1/1/1983',
 '7/1/1994',
 '12/1/2008',
 '10/1/1980',
 '8/1/2003',
 '12/1/1975',
 '11/1/2010',
 '7/1/1997',
 '7/1/2014',
 '9/1/2001',
 '8/1/1986',
 '1/1/1978',
 '9/1/1975',
 '1/1/2009',
 '5/1/1995',
 '8/1/1989',
 '11/1/2000',
 '06/1/1973',
 '2/1/1999',
 '6/1/2001',
 '12/1/1978',
 '8/1/2009',
 '7/1/1973',
 '1/1/2014',
 '09/1/1975',
 '12/1/2012',
 '5/1/1999',
 '7/1/1989',
 '7/1/2009',
 '11/1/1998',
 '3/1/1995',
 '2/1/2009',
 '08/1/1988',
 '4/1/2007',
 '5/1/2000',
 '4/1/2012',
 '10/1/2001',
 '2/1/1977',
 '8/1/2008',
 '2/1/1983',
 '5/1/1979',
 '1/1/1992',
 '11/1/2008',
 '12/1/2014',
 '4/1/1974',
 '10/1/1981',
 '10/1/1986',
 '03/1/1973',
 '12/1/1994',
 '8/1/1999',
 '10/1/2010',
 '10/1/1994',
 '01/1/2007',
 '8/1/2010',
 '03/1/1990',
 '11/1/2016',
 '4/1/2004',
 '2/1/1973',
 '7/1/1987',
 '8/1/2000',
 '8/1/1975',
 '5/1/1977',
 '3/1/2000',
 '9/1/1984',
 '4/1/1973',
 '12/1/1986',
 '4/1/1979',
 '7/1/2004',
 '11/1/1984',
 '5/1/2016',
 '12/1/2007',
 '11/1/1982',
 '06/1/1981',
 '4/1/2013',
 '4/1/1999',
 '5/1/2006',
 '10/1/1978',
 '12/1/1989',
 '2/1/1974',
 '11/1/1986',
 '4/1/1983',
 '10/1/2014',
 '6/1/1989',
 '9/1/1980',
 '9/1/1992',
 '9/1/2000',
 '7/1/1981',
 '1/1/2008',
 '4/1/2002',
 '7/1/1985',
 '5/1/2010',
 '8/1/2002',
 '1/1/1994',
 '12/1/2004',
 '3/1/2003',
 '7/1/1991',
 '7/1/1982',
 '1/1/1984',
 '1/1/2000',
 '1/1/2001',
 '1/1/1982',
 '1/1/1998',
 '1/1/2012',
 '1/1/1991',
 '1/1/1988',
 '1/1/2014',
 '1/1/2016',
 '1/1/1976',
 '1/1/1981',
 '1/1/2011',
 '1/1/1997',
 '1/1/2003',
 '1/1/1983',
 '1/1/1999',
 '1/1/2010',
 '1/1/1975',
 '1/1/1972',
 '1/1/2015',
 '1/1/1989',
 '1/1/1994',
 '1/1/1993',
 '1/1/1996',
 '1/1/2013',
 '1/1/1974',
 '1/1/1990',
 '1/1/1995',
 '1/1/2004',
 '1/1/1987',
 '1/1/1973',
 '1/1/1992',
 '1/1/1977',
 '1/1/1985',
 '1/1/2007',
 '1/1/2009',
 '1/1/1986',
 '1/1/1978',
 '1/1/2002',
 '1/1/1979',
 '1/1/2006',
 '1/1/2008',
 '1/1/2005',
 '1/1/1980']

In [12]:
d3=[]
for date in d2:
    if '-' in date:
        x=date.split('-')
        date='/'.join(x)
    x= date.split('/')
    y=x[-1]
    if len(y)==2:
        x[-1]='19'+y
    d3.append('/'.join(x))

In [13]:
d3

['03/25/1993',
 '6/18/1985',
 '7/8/1971',
 '9/27/1975',
 '2/6/1996',
 '7/06/1979',
 '5/18/1978',
 '10/24/1989',
 '3/7/1986',
 '4/10/1971',
 '5/11/1985',
 '4/09/1975',
 '8/01/1998',
 '1/26/1972',
 '5/24/1990',
 '1/25/2011',
 '4/12/1982',
 '10/13/1976',
 '4/24/1998',
 '5/21/1977',
 '7/21/1998',
 '10/21/1979',
 '3/03/1990',
 '2/11/1976',
 '07/25/1984',
 '4/13/1982',
 '9/22/1989',
 '9/02/1976',
 '9/12/1971',
 '10/24/1986',
 '03/31/1985',
 '7/20/1972',
 '4/12/1987',
 '06/20/1991',
 '5/12/2012',
 '3/15/1983',
 '2/14/1973',
 '5/24/1988',
 '7/27/1986',
 '1/14/1981',
 '7/29/1975',
 '6/24/1987',
 '8/14/1994',
 '4/13/2002',
 '8/16/1982',
 '2/15/1998',
 '7/15/1991',
 '06/12/1994',
 '9/17/1984',
 '2/28/1975',
 '11/22/1975',
 '5/24/1991',
 '6/13/1992',
 '7/11/1971',
 '12/26/1986',
 '10/11/1987',
 '3/14/1995',
 '12/01/1973',
 '12/5/2010',
 '08/20/1982',
 '7/24/1995',
 '8/06/1983',
 '02/22/1992',
 '6/28/1987',
 '07/29/1994',
 '08/11/1978',
 '10/29/1991',
 '7/6/1991',
 '1/21/1987',
 '11/3/1985',
 '7/04/1982',
 '4/13/1989',
 '7/11/1977',
 '4/12/1974',
 '09/19/1981',
 '9/6/1979',
 '12/5/1987',
 '01/05/1999',
 '4/22/1980',
 '10/04/1998',
 '6/29/1981',
 '8/04/1978',
 '7/07/1974',
 '09/14/2000',
 '5/18/1971',
 '8/09/1981',
 '6/05/1993',
 '8/9/1997',
 '12/8/1982',
 '8/26/1989',
 '10/13/1995',
 '4/19/1991',
 '04/08/2004',
 '9/20/1976',
 '12/08/1990',
 '4/11/1974',
 '7/18/1986',
 '3/31/1991',
 '5/13/1972',
 '11/14/1983',
 '8/16/1992',
 '10/05/1997',
 '07/18/2002',
 '9/22/1982',
 '2/24/1974',
 '2/03/1978',
 '2/11/2006',
 '8/22/1983',
 '5/04/1974',
 '7/20/2011',
 '6/17/1995',
 '6/10/1972',
 '10/16/1982',
 '12/15/1992',
 '12/8/1997',
 '4/05/1989',
 '12/04/1987',
 '6/20/1977',
 '4/27/2006',
 '07/17/1992',
 '12/22/1998',
 '10/02/1996',
 '11/05/1990',
 '5/04/1977',
 '2/27/1996',
 '01/24/2001',
 '09/10/2004',
 '05/26/1982',
 '06/28/2002',
 '05/06/1972',
 '10/25/1987',
 '10/14/1996',
 '11/30/2007',
 '06/28/1994',
 '01/14/1981',
 '10/10/1985',
 '02/11/1985',
 '02/10/1983',
 '02/05/1992',
 '10/21/2012',
 '02/14/1995',
 '05/30/2016',
 '01/22/1996',
 '10/14/1992',
 '10/06/2003',
 '10/18/1999',
 '11/11/2004',
 '05/30/2001',
 '02/02/1978',
 '09/09/1989',
 '03/12/1980',
 '06/22/1990',
 '09/28/2015',
 '01/13/1972',
 '03/06/1974',
 '10/10/1974',
 '05/26/1974',
 '02/10/1990',
 '08/23/2000',
 '05/26/2001',
 '10/21/2007',
 '10/19/2016',
 '03/05/1974',
 '01/29/1994',
 '10/21/1978',
 '08/18/1975',
 '11/11/1996',
 '10/01/1979',
 '10/13/1986',
 '10/21/1995',
 '01/24/2011',
 '10/04/1972',
 '08/23/1993',
 '10/18/2006',
 '12/04/1988',
 '10/21/1983',
 '05/26/2010',
 '01/18/1990',
 '06/15/1985',
 '12/10/1982',
 '12/09/1988',
 '08/18/1995',
 '06/13/1974',
 '05/26/2008',
 '11/11/2002',
 '08/17/1985',
 '10/13/2016',
 '01/14/2008',
 '03/12/2004',
 '10/21/1977',
 '08/10/2000',
 '11/30/1972',
 '05/06/1993',
 '01/18/1995',
 '04/11/1990',
 '05/30/2001',
 '02/18/1994',
 '02/18/1981',
 '10/11/2013',
 '01/24/1986',
 '07/26/1978',
 '12/23/1999',
 '05/15/1989',
 '09/06/1995',
 '03/10/1976',
 '01/27/1983',
 '10/23/1990',
 '08/12/2004',
 '09/01/2012',
 '07/25/1983',
 '08/11/1989',
 '04/17/1992',
 '07/24/1999',
 '07/11/1997',
 '09/10/1974',
 '08/14/1981',
 '11/11/1988',
 '06/13/2011',
 '05/14/1989',
 '12/14/1975',
 '06/25/2012',
 '10/18/1980',
 '05/15/1998',
 '10/14/1974',
 '07/25/1998',
 '06/15/1972',
 '01/07/1991',
 '09/15/2011',
 '1/1/1985',
 '1/1/2011',
 '1/1/1986',
 '1/1/2016',
 '1/1/1977',
 '1/1/1990',
 '1/1/2003',
 '1/1/2015',
 '1/1/1995',
 '1/1/1976',
 '1/1/1995',
 '1/1/1978',
 '1/1/2011',
 '1/1/2004',
 '1/1/2010',
 '1/1/2012',
 '1/1/2013',
 '1/1/1990',
 '1/1/1981',
 '1/1/1983',
 '1/1/1995',
 '1/1/1993',
 '1/1/2005',
 '1/1/1998',
 '1/1/2007',
 '1/1/2016',
 '1/1/1979',
 '1/1/2014',
 '1/1/1988',
 '1/1/2015',
 '1/1/1976',
 '1/1/1979',
 '1/1/2000',
 '1/1/1986',
 '1/1/2002',
 '1/1/1981',
 '1/1/2007',
 '1/1/1989',
 '1/1/1999',
 '1/1/1980',
 '1/1/2009',
 '1/1/1992',
 '1/1/2006',
 '1/1/7787',
 '1/1/1993',
 '1/1/2010',
 '1/1/1985',
 '1/1/1984',
 '1/1/1986',
 '1/1/2007',
 '1/1/1974',
 '1/1/2013',
 '1/1/1985',
 '1/1/2004',
 '1/1/2012',
 '1/1/1977',
 '1/1/1987',
 '1/1/1983',
 '1/1/2013',
 '1/1/2010',
 '1/1/2009',
 '1/1/2007',
 '1/1/2011',
 '1/1/2004',
 '1/1/1995',
 '1/1/2008',
 '1/1/1983',
 '1/1/1983',
 '1/1/1979',
 '1/1/2009',
 '1/1/1993',
 '1/1/1974',
 '1/1/1994',
 '1/1/1992',
 '1/1/2004',
 '1/1/1977',
 '1/1/2002',
 '1/1/2000',
 '1/1/2004',
 '1/1/2006',
 '1/1/1994',
 '1/1/1977',
 '1/1/1992',
 '1/1/1995',
 '1/1/1989',
 '1/1/1978',
 '1/1/2007',
 '1/1/1976',
 '1/1/2011',
 '1/1/1975',
 '1/1/1978',
 '1/1/1975',
 '1/1/2012',
 '6/2/1999',
 '1/1/1991',
 '1/1/1973',
 '1/1/1996',
 '1/1/2007',
 '1/1/1995',
 '1/1/1999',
 '1/1/2001',
 '1/1/2000',
 '1/1/1988',
 '1/1/1993',
 '1/1/1974',
 '1/1/1997',
 '1/1/1986',
 '1/1/1973',
 '1/1/1978',
 '1/1/2007',
 '1/1/1998',
 '1/1/2005',
 '1/1/1980',
 '1/1/2007',
 '1/1/1976',
 '6/1/1998',
 '6/1/2005',
 '10/1/1973',
 '9/1/2005',
 '03/1/1980',
 '12/1/2005',
 '5/1/1987',
 '5/1/2004',
 '8/1/1974',
 '3/1/1986',
 '10/1/1997',
 '3/1/1993',
 '3/1/1981',
 '9/1/2003',
 '10/1/1993',
 '1/1/1983',
 '7/1/1994',
 '12/1/2008',
 '10/1/1980',
 '8/1/2003',
 '12/1/1975',
 '11/1/2010',
 '7/1/1997',
 '7/1/2014',
 '9/1/2001',
 '8/1/1986',
 '1/1/1978',
 '9/1/1975',
 '1/1/2009',
 '5/1/1995',
 '8/1/1989',
 '11/1/2000',
 '06/1/1973',
 '2/1/1999',
 '6/1/2001',
 '12/1/1978',
 '8/1/2009',
 '7/1/1973',
 '1/1/2014',
 '09/1/1975',
 '12/1/2012',
 '5/1/1999',
 '7/1/1989',
 '7/1/2009',
 '11/1/1998',
 '3/1/1995',
 '2/1/2009',
 '08/1/1988',
 '4/1/2007',
 '5/1/2000',
 '4/1/2012',
 '10/1/2001',
 '2/1/1977',
 '8/1/2008',
 '2/1/1983',
 '5/1/1979',
 '1/1/1992',
 '11/1/2008',
 '12/1/2014',
 '4/1/1974',
 '10/1/1981',
 '10/1/1986',
 '03/1/1973',
 '12/1/1994',
 '8/1/1999',
 '10/1/2010',
 '10/1/1994',
 '01/1/2007',
 '8/1/2010',
 '03/1/1990',
 '11/1/2016',
 '4/1/2004',
 '2/1/1973',
 '7/1/1987',
 '8/1/2000',
 '8/1/1975',
 '5/1/1977',
 '3/1/2000',
 '9/1/1984',
 '4/1/1973',
 '12/1/1986',
 '4/1/1979',
 '7/1/2004',
 '11/1/1984',
 '5/1/2016',
 '12/1/2007',
 '11/1/1982',
 '06/1/1981',
 '4/1/2013',
 '4/1/1999',
 '5/1/2006',
 '10/1/1978',
 '12/1/1989',
 '2/1/1974',
 '11/1/1986',
 '4/1/1983',
 '10/1/2014',
 '6/1/1989',
 '9/1/1980',
 '9/1/1992',
 '9/1/2000',
 '7/1/1981',
 '1/1/2008',
 '4/1/2002',
 '7/1/1985',
 '5/1/2010',
 '8/1/2002',
 '1/1/1994',
 '12/1/2004',
 '3/1/2003',
 '7/1/1991',
 '7/1/1982',
 '1/1/1984',
 '1/1/2000',
 '1/1/2001',
 '1/1/1982',
 '1/1/1998',
 '1/1/2012',
 '1/1/1991',
 '1/1/1988',
 '1/1/2014',
 '1/1/2016',
 '1/1/1976',
 '1/1/1981',
 '1/1/2011',
 '1/1/1997',
 '1/1/2003',
 '1/1/1983',
 '1/1/1999',
 '1/1/2010',
 '1/1/1975',
 '1/1/1972',
 '1/1/2015',
 '1/1/1989',
 '1/1/1994',
 '1/1/1993',
 '1/1/1996',
 '1/1/2013',
 '1/1/1974',
 '1/1/1990',
 '1/1/1995',
 '1/1/2004',
 '1/1/1987',
 '1/1/1973',
 '1/1/1992',
 '1/1/1977',
 '1/1/1985',
 '1/1/2007',
 '1/1/2009',
 '1/1/1986',
 '1/1/1978',
 '1/1/2002',
 '1/1/1979',
 '1/1/2006',
 '1/1/2008',
 '1/1/2005',
 '1/1/1980']

In [25]:
d3[271]='8/1/2008'

In [26]:
d3[271]

'8/1/2008'

In [27]:
s2=pd.Series(d3)

In [28]:
s_new=pd.to_datetime(s2)

In [29]:
s_new

0     1993-03-25
1     1985-06-18
2     1971-07-08
3     1975-09-27
4     1996-02-06
         ...
495   1979-01-01
496   2006-01-01
497   2008-01-01
498   2005-01-01
499   1980-01-01
Length: 500, dtype: datetime64[ns]

In [42]:
s_new=pd.to_datetime(s2)

In [65]:
s_new2=pd.Series(sorted(s_new))

In [66]:
s_new2

0     1971-04-10
1     1971-05-18
2     1971-07-08
3     1971-07-11
4     1971-09-12
         ...
495   2016-05-01
496   2016-05-30
497   2016-10-13
498   2016-10-19
499   2016-11-01
Length: 500, dtype: datetime64[ns]

In [59]:
date_index={date:index for index,date in enumerate(s_new2)}

In [60]:
date_index

{Timestamp('1971-04-10 00:00:00'): 0,
 Timestamp('1971-05-18 00:00:00'): 1,
 Timestamp('1971-07-08 00:00:00'): 2,
 Timestamp('1971-07-11 00:00:00'): 3,
 Timestamp('1971-09-12 00:00:00'): 4,
 Timestamp('1972-01-01 00:00:00'): 5,
 Timestamp('1972-01-13 00:00:00'): 6,
 Timestamp('1972-01-26 00:00:00'): 7,
 Timestamp('1972-05-06 00:00:00'): 8,
 Timestamp('1972-05-13 00:00:00'): 9,
 Timestamp('1972-06-10 00:00:00'): 10,
 Timestamp('1972-06-15 00:00:00'): 11,
 Timestamp('1972-07-20 00:00:00'): 12,
 Timestamp('1972-10-04 00:00:00'): 13,
 Timestamp('1972-11-30 00:00:00'): 14,
 Timestamp('1973-01-01 00:00:00'): 17,
 Timestamp('1973-02-01 00:00:00'): 18,
 Timestamp('1973-02-14 00:00:00'): 19,
 Timestamp('1973-03-01 00:00:00'): 20,
 Timestamp('1973-04-01 00:00:00'): 21,
 Timestamp('1973-06-01 00:00:00'): 22,
 Timestamp('1973-07-01 00:00:00'): 23,
 Timestamp('1973-10-01 00:00:00'): 24,
 Timestamp('1973-12-01 00:00:00'): 25,
 Timestamp('1974-01-01 00:00:00'): 29,
 Timestamp('1974-02-01 00:00:00'): 30,
 Timestamp('1974-02-24 00:00:00'): 31,
 Timestamp('1974-03-05 00:00:00'): 32,
 Timestamp('1974-03-06 00:00:00'): 33,
 Timestamp('1974-04-01 00:00:00'): 34,
 Timestamp('1974-04-11 00:00:00'): 35,
 Timestamp('1974-04-12 00:00:00'): 36,
 Timestamp('1974-05-04 00:00:00'): 37,
 Timestamp('1974-05-26 00:00:00'): 38,
 Timestamp('1974-06-13 00:00:00'): 39,
 Timestamp('1974-07-07 00:00:00'): 40,
 Timestamp('1974-08-01 00:00:00'): 41,
 Timestamp('1974-09-10 00:00:00'): 42,
 Timestamp('1974-10-10 00:00:00'): 43,
 Timestamp('1974-10-14 00:00:00'): 44,
 Timestamp('1975-01-01 00:00:00'): 47,
 Timestamp('1975-02-28 00:00:00'): 48,
 Timestamp('1975-04-09 00:00:00'): 49,
 Timestamp('1975-07-29 00:00:00'): 50,
 Timestamp('1975-08-01 00:00:00'): 51,
 Timestamp('1975-08-18 00:00:00'): 52,
 Timestamp('1975-09-01 00:00:00'): 54,
 Timestamp('1975-09-27 00:00:00'): 55,
 Timestamp('1975-11-22 00:00:00'): 56,
 Timestamp('1975-12-01 00:00:00'): 57,
 Timestamp('1975-12-14 00:00:00'): 58,
 Timestamp('1976-01-01 00:00:00'): 63,
 Timestamp('1976-02-11 00:00:00'): 64,
 Timestamp('1976-03-10 00:00:00'): 65,
 Timestamp('1976-09-02 00:00:00'): 66,
 Timestamp('1976-09-20 00:00:00'): 67,
 Timestamp('1976-10-13 00:00:00'): 68,
 Timestamp('1977-01-01 00:00:00'): 73,
 Timestamp('1977-02-01 00:00:00'): 74,
 Timestamp('1977-05-01 00:00:00'): 75,
 Timestamp('1977-05-04 00:00:00'): 76,
 Timestamp('1977-05-21 00:00:00'): 77,
 Timestamp('1977-06-20 00:00:00'): 78,
 Timestamp('1977-07-11 00:00:00'): 79,
 Timestamp('1977-10-21 00:00:00'): 80,
 Timestamp('1978-01-01 00:00:00'): 86,
 Timestamp('1978-02-02 00:00:00'): 87,
 Timestamp('1978-02-03 00:00:00'): 88,
 Timestamp('1978-05-18 00:00:00'): 89,
 Timestamp('1978-07-26 00:00:00'): 90,
 Timestamp('1978-08-04 00:00:00'): 91,
 Timestamp('1978-08-11 00:00:00'): 92,
 Timestamp('1978-10-01 00:00:00'): 93,
 Timestamp('1978-10-21 00:00:00'): 94,
 Timestamp('1978-12-01 00:00:00'): 95,
 Timestamp('1979-01-01 00:00:00'): 99,
 Timestamp('1979-04-01 00:00:00'): 100,
 Timestamp('1979-05-01 00:00:00'): 101,
 Timestamp('1979-07-06 00:00:00'): 102,
 Timestamp('1979-09-06 00:00:00'): 103,
 Timestamp('1979-10-01 00:00:00'): 104,
 Timestamp('1979-10-21 00:00:00'): 105,
 Timestamp('1980-01-01 00:00:00'): 108,
 Timestamp('1980-03-01 00:00:00'): 109,
 Timestamp('1980-03-12 00:00:00'): 110,
 Timestamp('1980-04-22 00:00:00'): 111,
 Timestamp('1980-09-01 00:00:00'): 112,
 Timestamp('1980-10-01 00:00:00'): 113,
 Timestamp('1980-10-18 00:00:00'): 114,
 Timestamp('1981-01-01 00:00:00'): 117,
 Timestamp('1981-01-14 00:00:00'): 119,
 Timestamp('1981-02-18 00:00:00'): 120,
 Timestamp('1981-03-01 00:00:00'): 121,
 Timestamp('1981-06-01 00:00:00'): 122,
 Timestamp('1981-06-29 00:00:00'): 123,
 Timestamp('1981-07-01 00:00:00'): 124,
 Timestamp('1981-08-09 00:00:00'): 125,
 Timestamp('1981-08-14 00:00:00'): 126,
 Timestamp('1981-09-19 00:00:00'): 127,
 Timestamp('1981-10-01 00:00:00'): 128,
 Timestamp('1982-01-01 00:00:00'): 129,
 Timestamp('1982-04-12 00:00:00'): 130,
 Timestamp('1982-04-13 00:00:00'): 131,
 Timestamp('1982-05-26 00:00:00'): 132,
 Timestamp('1982-07-01 00:00:00'): 133,
 Timestamp('1982-07-04 00:00:00'): 134,
 Timestamp('1982-08-16 00:00:00'): 135,
 Timestamp('1982-08-20 00:00:00'): 136,
 Timestamp('1982-09-22 00:00:00'): 137,
 Timestamp('1982-10-16 00:00:00'): 138,
 Timestamp('1982-11-01 00:00:00'): 139,
 Timestamp('1982-12-08 00:00:00'): 140,
 Timestamp('1982-12-10 00:00:00'): 141,
 Timestamp('1983-01-01 00:00:00'): 147,
 Timestamp('1983-01-27 00:00:00'): 148,
 Timestamp('1983-02-01 00:00:00'): 149,
 Timestamp('1983-02-10 00:00:00'): 150,
 Timestamp('1983-03-15 00:00:00'): 151,
 Timestamp('1983-04-01 00:00:00'): 152,
 Timestamp('1983-07-25 00:00:00'): 153,
 Timestamp('1983-08-06 00:00:00'): 154,
 Timestamp('1983-08-22 00:00:00'): 155,
 Timestamp('1983-10-21 00:00:00'): 156,
 Timestamp('1983-11-14 00:00:00'): 157,
 Timestamp('1984-01-01 00:00:00'): 159,
 Timestamp('1984-07-25 00:00:00'): 160,
 Timestamp('1984-09-01 00:00:00'): 161,
 Timestamp('1984-09-17 00:00:00'): 162,
 Timestamp('1984-11-01 00:00:00'): 163,
 Timestamp('1985-01-01 00:00:00'): 167,
 Timestamp('1985-02-11 00:00:00'): 168,
 Timestamp('1985-03-31 00:00:00'): 169,
 Timestamp('1985-05-11 00:00:00'): 170,
 Timestamp('1985-06-15 00:00:00'): 171,
 Timestamp('1985-06-18 00:00:00'): 172,
 Timestamp('1985-07-01 00:00:00'): 173,
 Timestamp('1985-08-17 00:00:00'): 174,
 Timestamp('1985-10-10 00:00:00'): 175,
 Timestamp('1985-11-03 00:00:00'): 176,
 Timestamp('1986-01-01 00:00:00'): 181,
 Timestamp('1986-01-24 00:00:00'): 182,
 Timestamp('1986-03-01 00:00:00'): 183,
 Timestamp('1986-03-07 00:00:00'): 184,
 Timestamp('1986-07-18 00:00:00'): 185,
 Timestamp('1986-07-27 00:00:00'): 186,
 Timestamp('1986-08-01 00:00:00'): 187,
 Timestamp('1986-10-01 00:00:00'): 188,
 Timestamp('1986-10-13 00:00:00'): 189,
 Timestamp('1986-10-24 00:00:00'): 190,
 Timestamp('1986-11-01 00:00:00'): 191,
 Timestamp('1986-12-01 00:00:00'): 192,
 Timestamp('1986-12-26 00:00:00'): 193,
 Timestamp('1987-01-01 00:00:00'): 195,
 Timestamp('1987-01-21 00:00:00'): 196,
 Timestamp('1987-04-12 00:00:00'): 197,
 Timestamp('1987-05-01 00:00:00'): 198,
 Timestamp('1987-06-24 00:00:00'): 199,
 Timestamp('1987-06-28 00:00:00'): 200,
 Timestamp('1987-07-01 00:00:00'): 201,
 Timestamp('1987-10-11 00:00:00'): 202,
 Timestamp('1987-10-25 00:00:00'): 203,
 Timestamp('1987-12-04 00:00:00'): 204,
 Timestamp('1987-12-05 00:00:00'): 205,
 Timestamp('1988-01-01 00:00:00'): 208,
 Timestamp('1988-05-24 00:00:00'): 209,
 Timestamp('1988-08-01 00:00:00'): 210,
 Timestamp('1988-11-11 00:00:00'): 211,
 Timestamp('1988-12-04 00:00:00'): 212,
 Timestamp('1988-12-09 00:00:00'): 213,
 Timestamp('1989-01-01 00:00:00'): 216,
 Timestamp('1989-04-05 00:00:00'): 217,
 Timestamp('1989-04-13 00:00:00'): 218,
 Timestamp('1989-05-14 00:00:00'): 219,
 Timestamp('1989-05-15 00:00:00'): 220,
 Timestamp('1989-06-01 00:00:00'): 221,
 Timestamp('1989-07-01 00:00:00'): 222,
 Timestamp('1989-08-01 00:00:00'): 223,
 Timestamp('1989-08-11 00:00:00'): 224,
 Timestamp('1989-08-26 00:00:00'): 225,
 Timestamp('1989-09-09 00:00:00'): 226,
 Timestamp('1989-09-22 00:00:00'): 227,
 Timestamp('1989-10-24 00:00:00'): 228,
 Timestamp('1989-12-01 00:00:00'): 229,
 Timestamp('1990-01-01 00:00:00'): 232,
 Timestamp('1990-01-18 00:00:00'): 233,
 Timestamp('1990-02-10 00:00:00'): 234,
 Timestamp('1990-03-01 00:00:00'): 235,
 Timestamp('1990-03-03 00:00:00'): 236,
 Timestamp('1990-04-11 00:00:00'): 237,
 Timestamp('1990-05-24 00:00:00'): 238,
 Timestamp('1990-06-22 00:00:00'): 239,
 Timestamp('1990-10-23 00:00:00'): 240,
 Timestamp('1990-11-05 00:00:00'): 241,
 Timestamp('1990-12-08 00:00:00'): 242,
 Timestamp('1991-01-01 00:00:00'): 244,
 Timestamp('1991-01-07 00:00:00'): 245,
 Timestamp('1991-03-31 00:00:00'): 246,
 Timestamp('1991-04-19 00:00:00'): 247,
 Timestamp('1991-05-24 00:00:00'): 248,
 Timestamp('1991-06-20 00:00:00'): 249,
 Timestamp('1991-07-01 00:00:00'): 250,
 Timestamp('1991-07-06 00:00:00'): 251,
 Timestamp('1991-07-15 00:00:00'): 252,
 Timestamp('1991-10-29 00:00:00'): 253,
 Timestamp('1992-01-01 00:00:00'): 258,
 Timestamp('1992-02-05 00:00:00'): 259,
 Timestamp('1992-02-22 00:00:00'): 260,
 Timestamp('1992-04-17 00:00:00'): 261,
 Timestamp('1992-06-13 00:00:00'): 262,
 Timestamp('1992-07-17 00:00:00'): 263,
 Timestamp('1992-08-16 00:00:00'): 264,
 Timestamp('1992-09-01 00:00:00'): 265,
 Timestamp('1992-10-14 00:00:00'): 266,
 Timestamp('1992-12-15 00:00:00'): 267,
 Timestamp('1993-01-01 00:00:00'): 272,
 Timestamp('1993-03-01 00:00:00'): 273,
 Timestamp('1993-03-25 00:00:00'): 274,
 Timestamp('1993-05-06 00:00:00'): 275,
 Timestamp('1993-06-05 00:00:00'): 276,
 Timestamp('1993-08-23 00:00:00'): 277,
 Timestamp('1993-10-01 00:00:00'): 278,
 Timestamp('1994-01-01 00:00:00'): 282,
 Timestamp('1994-01-29 00:00:00'): 283,
 Timestamp('1994-02-18 00:00:00'): 284,
 Timestamp('1994-06-12 00:00:00'): 285,
 Timestamp('1994-06-28 00:00:00'): 286,
 Timestamp('1994-07-01 00:00:00'): 287,
 Timestamp('1994-07-29 00:00:00'): 288,
 Timestamp('1994-08-14 00:00:00'): 289,
 Timestamp('1994-10-01 00:00:00'): 290,
 Timestamp('1994-12-01 00:00:00'): 291,
 Timestamp('1995-01-01 00:00:00'): 298,
 Timestamp('1995-01-18 00:00:00'): 299,
 Timestamp('1995-02-14 00:00:00'): 300,
 Timestamp('1995-03-01 00:00:00'): 301,
 Timestamp('1995-03-14 00:00:00'): 302,
 Timestamp('1995-05-01 00:00:00'): 303,
 Timestamp('1995-06-17 00:00:00'): 304,
 Timestamp('1995-07-24 00:00:00'): 305,
 Timestamp('1995-08-18 00:00:00'): 306,
 Timestamp('1995-09-06 00:00:00'): 307,
 Timestamp('1995-10-13 00:00:00'): 308,
 Timestamp('1995-10-21 00:00:00'): 309,
 Timestamp('1996-01-01 00:00:00'): 311,
 Timestamp('1996-01-22 00:00:00'): 312,
 Timestamp('1996-02-06 00:00:00'): 313,
 Timestamp('1996-02-27 00:00:00'): 314,
 Timestamp('1996-10-02 00:00:00'): 315,
 Timestamp('1996-10-14 00:00:00'): 316,
 Timestamp('1996-11-11 00:00:00'): 317,
 Timestamp('1997-01-01 00:00:00'): 319,
 Timestamp('1997-07-01 00:00:00'): 320,
 Timestamp('1997-07-11 00:00:00'): 321,
 Timestamp('1997-08-09 00:00:00'): 322,
 Timestamp('1997-10-01 00:00:00'): 323,
 Timestamp('1997-10-05 00:00:00'): 324,
 Timestamp('1997-12-08 00:00:00'): 325,
 Timestamp('1998-01-01 00:00:00'): 328,
 Timestamp('1998-02-15 00:00:00'): 329,
 Timestamp('1998-04-24 00:00:00'): 330,
 Timestamp('1998-05-15 00:00:00'): 331,
 Timestamp('1998-06-01 00:00:00'): 332,
 Timestamp('1998-07-21 00:00:00'): 333,
 Timestamp('1998-07-25 00:00:00'): 334,
 Timestamp('1998-08-01 00:00:00'): 335,
 Timestamp('1998-10-04 00:00:00'): 336,
 Timestamp('1998-11-01 00:00:00'): 337,
 Timestamp('1998-12-22 00:00:00'): 338,
 Timestamp('1999-01-01 00:00:00'): 341,
 Timestamp('1999-01-05 00:00:00'): 342,
 Timestamp('1999-02-01 00:00:00'): 343,
 Timestamp('1999-04-01 00:00:00'): 344,
 Timestamp('1999-05-01 00:00:00'): 345,
 Timestamp('1999-06-02 00:00:00'): 346,
 Timestamp('1999-07-24 00:00:00'): 347,
 Timestamp('1999-08-01 00:00:00'): 348,
 Timestamp('1999-10-18 00:00:00'): 349,
 Timestamp('1999-12-23 00:00:00'): 350,
 Timestamp('2000-01-01 00:00:00'): 354,
 Timestamp('2000-03-01 00:00:00'): 355,
 Timestamp('2000-05-01 00:00:00'): 356,
 Timestamp('2000-08-01 00:00:00'): 357,
 Timestamp('2000-08-10 00:00:00'): 358,
 Timestamp('2000-08-23 00:00:00'): 359,
 Timestamp('2000-09-01 00:00:00'): 360,
 Timestamp('2000-09-14 00:00:00'): 361,
 Timestamp('2000-11-01 00:00:00'): 362,
 Timestamp('2001-01-01 00:00:00'): 364,
 Timestamp('2001-01-24 00:00:00'): 365,
 Timestamp('2001-05-26 00:00:00'): 366,
 Timestamp('2001-05-30 00:00:00'): 368,
 Timestamp('2001-06-01 00:00:00'): 369,
 Timestamp('2001-09-01 00:00:00'): 370,
 Timestamp('2001-10-01 00:00:00'): 371,
 Timestamp('2002-01-01 00:00:00'): 374,
 Timestamp('2002-04-01 00:00:00'): 375,
 Timestamp('2002-04-13 00:00:00'): 376,
 Timestamp('2002-06-28 00:00:00'): 377,
 Timestamp('2002-07-18 00:00:00'): 378,
 Timestamp('2002-08-01 00:00:00'): 379,
 Timestamp('2002-11-11 00:00:00'): 380,
 Timestamp('2003-01-01 00:00:00'): 382,
 Timestamp('2003-03-01 00:00:00'): 383,
 Timestamp('2003-08-01 00:00:00'): 384,
 Timestamp('2003-09-01 00:00:00'): 385,
 Timestamp('2003-10-06 00:00:00'): 386,
 Timestamp('2004-01-01 00:00:00'): 392,
 Timestamp('2004-03-12 00:00:00'): 393,
 Timestamp('2004-04-01 00:00:00'): 394,
 Timestamp('2004-04-08 00:00:00'): 395,
 Timestamp('2004-05-01 00:00:00'): 396,
 Timestamp('2004-07-01 00:00:00'): 397,
 Timestamp('2004-08-12 00:00:00'): 398,
 Timestamp('2004-09-10 00:00:00'): 399,
 Timestamp('2004-11-11 00:00:00'): 400,
 Timestamp('2004-12-01 00:00:00'): 401,
 Timestamp('2005-01-01 00:00:00'): 404,
 Timestamp('2005-06-01 00:00:00'): 405,
 Timestamp('2005-09-01 00:00:00'): 406,
 Timestamp('2005-12-01 00:00:00'): 407,
 Timestamp('2006-01-01 00:00:00'): 410,
 Timestamp('2006-02-11 00:00:00'): 411,
 Timestamp('2006-04-27 00:00:00'): 412,
 Timestamp('2006-05-01 00:00:00'): 413,
 Timestamp('2006-10-18 00:00:00'): 414,
 Timestamp('2007-01-01 00:00:00'): 424,
 Timestamp('2007-04-01 00:00:00'): 425,
 Timestamp('2007-10-21 00:00:00'): 426,
 Timestamp('2007-11-30 00:00:00'): 427,
 Timestamp('2007-12-01 00:00:00'): 428,
 Timestamp('2008-01-01 00:00:00'): 431,
 Timestamp('2008-01-14 00:00:00'): 432,
 Timestamp('2008-05-26 00:00:00'): 433,
 Timestamp('2008-08-01 00:00:00'): 435,
 Timestamp('2008-11-01 00:00:00'): 436,
 Timestamp('2008-12-01 00:00:00'): 437,
 Timestamp('2009-01-01 00:00:00'): 442,
 Timestamp('2009-02-01 00:00:00'): 443,
 Timestamp('2009-07-01 00:00:00'): 444,
 Timestamp('2009-08-01 00:00:00'): 445,
 Timestamp('2010-01-01 00:00:00'): 449,
 Timestamp('2010-05-01 00:00:00'): 450,
 Timestamp('2010-05-26 00:00:00'): 451,
 Timestamp('2010-08-01 00:00:00'): 452,
 Timestamp('2010-10-01 00:00:00'): 453,
 Timestamp('2010-11-01 00:00:00'): 454,
 Timestamp('2010-12-05 00:00:00'): 455,
 Timestamp('2011-01-01 00:00:00'): 460,
 Timestamp('2011-01-24 00:00:00'): 461,
 Timestamp('2011-01-25 00:00:00'): 462,
 Timestamp('2011-06-13 00:00:00'): 463,
 Timestamp('2011-07-20 00:00:00'): 464,
 Timestamp('2011-09-15 00:00:00'): 465,
 Timestamp('2012-01-01 00:00:00'): 469,
 Timestamp('2012-04-01 00:00:00'): 470,
 Timestamp('2012-05-12 00:00:00'): 471,
 Timestamp('2012-06-25 00:00:00'): 472,
 Timestamp('2012-09-01 00:00:00'): 473,
 Timestamp('2012-10-21 00:00:00'): 474,
 Timestamp('2012-12-01 00:00:00'): 475,
 Timestamp('2013-01-01 00:00:00'): 479,
 Timestamp('2013-04-01 00:00:00'): 480,
 Timestamp('2013-10-11 00:00:00'): 481,
 Timestamp('2014-01-01 00:00:00'): 484,
 Timestamp('2014-07-01 00:00:00'): 485,
 Timestamp('2014-10-01 00:00:00'): 486,
 Timestamp('2014-12-01 00:00:00'): 487,
 Timestamp('2015-01-01 00:00:00'): 490,
 Timestamp('2015-09-28 00:00:00'): 491,
 Timestamp('2016-01-01 00:00:00'): 494,
 Timestamp('2016-05-01 00:00:00'): 495,
 Timestamp('2016-05-30 00:00:00'): 496,
 Timestamp('2016-10-13 00:00:00'): 497,
 Timestamp('2016-10-19 00:00:00'): 498,
 Timestamp('2016-11-01 00:00:00'): 499}

In [62]:
l=[]
for x in s_new:
    l.append(date_index[x])

In [63]:
l

[274,
 172,
 2,
 55,
 313,
 102,
 89,
 228,
 184,
 0,
 170,
 49,
 335,
 7,
 238,
 462,
 130,
 68,
 330,
 77,
 333,
 105,
 236,
 64,
 160,
 131,
 227,
 66,
 4,
 190,
 169,
 12,
 197,
 249,
 471,
 151,
 19,
 209,
 186,
 119,
 50,
 199,
 289,
 376,
 135,
 329,
 252,
 285,
 162,
 48,
 56,
 248,
 262,
 3,
 193,
 202,
 302,
 25,
 455,
 136,
 305,
 154,
 260,
 200,
 288,
 92,
 253,
 251,
 196,
 176,
 134,
 218,
 79,
 36,
 127,
 103,
 205,
 342,
 111,
 336,
 123,
 91,
 40,
 361,
 1,
 125,
 276,
 322,
 140,
 225,
 308,
 247,
 395,
 67,
 242,
 35,
 185,
 246,
 9,
 157,
 264,
 324,
 378,
 137,
 31,
 88,
 411,
 155,
 37,
 464,
 304,
 10,
 138,
 267,
 325,
 217,
 204,
 78,
 412,
 263,
 338,
 315,
 241,
 76,
 314,
 365,
 399,
 132,
 377,
 8,
 203,
 316,
 427,
 286,
 119,
 175,
 168,
 150,
 259,
 474,
 300,
 496,
 312,
 266,
 386,
 349,
 400,
 368,
 87,
 226,
 110,
 239,
 491,
 6,
 33,
 43,
 38,
 234,
 359,
 366,
 426,
 498,
 32,
 283,
 94,
 52,
 317,
 104,
 189,
 309,
 461,
 13,
 277,
 414,
 212,
 156,
 451,
 233,
 171,
 141,
 213,
 306,
 39,
 433,
 380,
 174,
 497,
 432,
 393,
 80,
 358,
 14,
 275,
 299,
 237,
 368,
 284,
 120,
 481,
 182,
 90,
 350,
 220,
 307,
 65,
 148,
 240,
 398,
 473,
 153,
 224,
 261,
 347,
 321,
 42,
 126,
 211,
 463,
 219,
 58,
 472,
 114,
 331,
 44,
 334,
 11,
 245,
 465,
 167,
 460,
 181,
 494,
 73,
 232,
 382,
 490,
 298,
 63,
 298,
 86,
 460,
 392,
 449,
 469,
 479,
 232,
 117,
 147,
 298,
 272,
 404,
 328,
 424,
 494,
 99,
 484,
 208,
 490,
 63,
 99,
 354,
 181,
 374,
 117,
 424,
 216,
 341,
 108,
 442,
 258,
 410,
 435,
 272,
 449,
 167,
 159,
 181,
 424,
 29,
 479,
 167,
 392,
 469,
 73,
 195,
 147,
 479,
 449,
 442,
 424,
 460,
 392,
 298,
 431,
 147,
 147,
 99,
 442,
 272,
 29,
 282,
 258,
 392,
 73,
 374,
 354,
 392,
 410,
 282,
 73,
 258,
 298,
 216,
 86,
 424,
 63,
 460,
 47,
 86,
 47,
 469,
 346,
 244,
 17,
 311,
 424,
 298,
 341,
 364,
 354,
 208,
 272,
 29,
 319,
 181,
 17,
 86,
 424,
 328,
 404,
 108,
 424,
 63,
 332,
 405,
 24,
 406,
 109,
 407,
 198,
 396,
 41,
 183,
 323,
 273,
 121,
 385,
 278,
 147,
 287,
 437,
 113,
 384,
 57,
 454,
 320,
 485,
 370,
 187,
 86,
 54,
 442,
 303,
 223,
 362,
 22,
 343,
 369,
 95,
 445,
 23,
 484,
 54,
 475,
 345,
 222,
 444,
 337,
 301,
 443,
 210,
 425,
 356,
 470,
 371,
 74,
 435,
 149,
 101,
 258,
 436,
 487,
 34,
 128,
 188,
 20,
 291,
 348,
 453,
 290,
 424,
 452,
 235,
 499,
 394,
 18,
 201,
 357,
 51,
 75,
 355,
 161,
 21,
 192,
 100,
 397,
 163,
 495,
 428,
 139,
 122,
 480,
 344,
 413,
 93,
 229,
 30,
 191,
 152,
 486,
 221,
 112,
 265,
 360,
 124,
 431,
 375,
 173,
 450,
 379,
 282,
 401,
 383,
 250,
 133,
 159,
 354,
 364,
 129,
 328,
 469,
 244,
 208,
 484,
 494,
 63,
 117,
 460,
 319,
 382,
 147,
 341,
 449,
 47,
 5,
 490,
 216,
 282,
 272,
 311,
 479,
 29,
 232,
 298,
 392,
 195,
 17,
 258,
 73,
 167,
 424,
 442,
 181,
 86,
 374,
 99,
 410,
 431,
 404,
 108]

In [64]:
pd.Series(l)

0      274
1      172
2        2
3       55
4      313
      ...
495     99
496    410
497    431
498    404
499    108
Length: 500, dtype: int64